--- #YAML:1.0
name:               DBIx-Array
version:            0.23
abstract:           This module is a wrapper around DBI with array interfaces
author:
    - Michael R. Davis (domain=>stopllc,tld=>com,account=>mdavis)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::CSV:      0
    DBI:           0
    Test::Simple:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
